version: '3'

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
      MYSQL_USER: blog
      MYSQL_PASSWORD: blog
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - "6379:6379"
